# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/intranet-webapp/MediaLibrary.Intranet.Web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/internet-webapp/MediaLibrary.Internet.Web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
  - package-ecosystem: "nuget"
    directory: "/internet-webapp/MediaLibrary.Internet.Api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/internet-webapp/MediaLibrary.Internet.Tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/internet-webapp/MediaLibrary.Internet.Web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/intranet-webapp/MediaLibrary.Intranet.Tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/intranet-webapp/MediaLibrary.Intranet.Web"
    schedule:
      interval: "weekly"
